aws_region            = "us-west-2"
aws_s3_log_bucket     = "otd268"
aws_cli_profile       = "dev"
aws_s3_bucket         = "otd268"
image_receipe_version = "1.0.0" # increatment each time you have an update
share_accounts = "433840313807"
ec2_iam_role_name = "svc-image-builder-role"
ebs_root_vol_size = 10
aws_key_pair_name = "image-builder-kp"
ami_name_tag      = "amzn-linux2"